apiVersion: v1
kind: Service
metadata:
  name: wordpress
  #namespace: wp 
  labels:
    app: wordpress
spec:
  #externalIPs:
  #  - x.x.x.x # Public IP of my Mac
  ports:
    - name: http
      protocol: TCP
      port: 80
      #targetPort: wdport 
      nodePort: 30036
  selector:
    app: wordpress
    tier: frontend
  #type: LoadBalancer
  #loadBalancerIP: x.x.x.x
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  #namespace: wp 
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:latest
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql:3306
      #   value: 10.152.183.58:3306  #wordpress-mysql
       #- name: WORDPRESS_DB_USER
       #  value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value:  
          #valueFrom:
          #  secretKeyRef:
          #    name: mysql-pass
          #    key: password
        ports:
        - containerPort: 80
          name: wdport
        volumeMounts:
        - name: uploads-ini
          mountPath: /usr/local/etc/php/conf.d/uploads.ini
        - name: wp-content
          mountPath: /var/www/html/wp-content
      volumes:
      - name: uploads-ini
        hostPath:
          path: /home/jerry/wp-k8s/uploads.ini
          type: File
      - name: wp-content
        hostPath:
          path: /home/jerry/wp-k8s/wp-content
          type: Directory
